name: Update News Data

on:
  schedule:
    # Run twice daily at 8:00 AM and 6:00 PM UTC
    - cron: '0 8,18 * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  collect-and-process:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download it_core_news_sm
        python -c "import nltk; nltk.download('stopwords'); nltk.download('punkt')"
    
    - name: Collect news data
      run: python scripts/collect_news.py
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
    
    - name: Process topics
      run: python scripts/process_topics.py
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        TOPIC_ALGORITHM: lda
        NUM_TOPICS: 10
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add data/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update data: $(date)"
        git push
